language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements.txt
script:
  - flake8 .
#  - python homework5/manage.py check
#  - python homework5/manage.py makemigrations --check --dry-run
