# Generated by Django 3.2 on 2021-04-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='sale',
            new_name='sell',
        ),
        migrations.AlterField(
            model_name='currency',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'MONOBANK'), (2, 'VKURSE'), (3, 'YAHOO')]),
        ),
    ]
